### ISSUE TITLE
Touchscreen

### ISSUE THREAD

**Issue by WilsontheWolf** [JsSucks/BetterDiscordApp#185]
I have diagnosed that better discord disables the touchscreen on win 10. Could someone please take a look at this for me.

**Comment by intrnl** [comment]
You got any proof of that?
BetterDiscord only messes with Discord, and nothing else.

Also, this is not the place for you to put issues like these.

**Comment by WilsontheWolf** [comment]
it disables on discord. I messed around with it and when I installed it the touchscreen didn't work (on discord) and when I reinstalled discord it worked. I then once again installed better discord and it didnt work.

**Comment by Modder4869** [comment]
smh,, don't use BD then or put your issue in the right place

**Comment by WilsontheWolf** [comment]
where would the right place be?

**Comment by Modder4869** [comment]
anywhere but not BDv2 repo that is not even released yet , join BD support server link
in https://github.com/Jiiks/BetterDiscordApp

**Comment by WilsontheWolf** [comment]
ok ill move it there. thanks
