### ISSUE TITLE
Support for Discord Portable

### ISSUE THREAD

**Issue by ezsnipes** [JsSucks/BetterDiscordApp#189]
I'm using the portable version of Discord.
When trying to install BetterDiscordApp the installer crashes:
`C:\Users\ezpz\AppData\Roaming\discord  - Directory not found`

The portable version of Discord uses the following path to store its data:

`C:\Users\ezpz\AppData\Roaming\discordptb`

I tried to build BetterDiscordApp on my own - but w/o success - otherwise I'd adjust the path & try it again with my own build.

Would be nice to have support for the portable version aswell. 
In case I get the build to work & I can fix the path issue, I can contribute this via PR (if desired)

Regards

**Comment by Modder4869** [comment]
wrong repo smh

**Comment by rauenzi** [comment]
Is this in regards to BDv2 or current version of BD?

Also PTB is not portable it's the public test beta.

**Comment by ezsnipes** [comment]
@Modder4869 I must have messed up the repos, thanks for pointing out...

@rauenzi Thanks for pointing that out. I'll adjust the issue name.

Furthermore, I was trying to install v0.3.0 (latest as of now) - just creating the folder (w/o content) fixes the crash which previously occurred when running the installer. 
During the installation process one can select whether to setup stable/ptb/canary.

Closing this issue then.
