### ISSUE TITLE
Download node through command prompt using curl??

### ISSUE THREAD

**Issue by DrunkenPoney** [JsSucks/BetterDiscordApp#192]
Would it be possible to download node using a CURL request instead of openning the browser? I tried it using the command prompt and it worked perfectly so I suppose it would work in node too.
I used the followind command to download node:
`curl https://nodejs.org/dist/v9.11.1/node-v9.11.1-x64.msi > node-v9.11.1-x64.msi`

I think the _code_ process would be like following:
Download node using curl. Once it's downloaded run the installer. Wait for the node installer process to be ended. Check if node has been correctly installed. And then....

It's just a suggestion, I don't really know how it's working actually and I don't even know if it would be possible. I thought maybe it could be helpful... and maybe not... i don't know.

**Comment by DrunkenPoney** [comment]
but msiexec wouldn't work on linux

**Comment by intrnl** [comment]
wouldn't you use a package manager to install node anyway

**Comment by Jiiks** [comment]
So what do we use to install curl...?

**Comment by Mondanzo** [comment]
You could make it OS specific.

So on Windows it would use msiexec,
on Linux and Mac curl
and if it's not installed you just use apt or brew.. i guess?

**Comment by DrunkenPoney** [comment]
`apt-get` works on the terminal of my android so I suppose it would work on linux and mac

**Comment by zerebos** [comment]
I think this is safe to close as we've gone in a much more realistic direction for the installation process.
