### ISSUE TITLE
No matter what I do, I get this error now and my theme won't load... :/

### ISSUE THREAD

**Issue by KyoumiOnism** [JsSucks/BetterDiscordApp#193]
![c77c483ed0f81417615221fd5f72c12a](https://user-images.githubusercontent.com/35385943/39163049-46abf51c-473e-11e8-83c1-205ea96c4fb0.png)

**Comment by rauenzi** [comment]
Wrong repo, go to https://github.com/Jiiks/BetterDiscordApp or better yet go to the dedicated support servers.

**Comment by KyoumiOnism** [comment]
I did that and it's still giving me this same error!

**Comment by rauenzi** [comment]
This is not the right repo for your issue. Visit the support servers for help.
