### ISSUE TITLE
Themes are broken

### ISSUE THREAD

**Issue by iiDxrkKnight** [JsSucks/BetterDiscordApp#197]
So when I tried to load up discord the themes where there,but it wasn't transparent and most of the theme was the original theme and I don't know if the plugin needs to be updated or BetterDiscord is down right now.If anyone can help me with this issue I would really appreciate it!

**Comment by rauenzi** [comment]
You're on the wrong repo. I suggest going to BD's support servers but it sounds like the theme just needs to be updated.

**Comment by iiDxrkKnight** [comment]
Oh ok,thank you for telling me this! :)
