### ISSUE TITLE
Better discord overlay

### ISSUE THREAD

**Issue by lewdxd** [JsSucks/BetterDiscordApp#257]
When I open overwatch, theres a huge thing blocking my game, and the betterdiscord logo can be seen at the bottom right.
![screenshot 2018-10-19 15 55 20](https://user-images.githubusercontent.com/44287498/47205042-74fcca80-d3b7-11e8-8689-7c21856f00b6.png)

**Comment by qwerasd205** [comment]
This issue is on the wrong repo, the issue you're experiencing is with https://github.com/rauenzi/BetterDiscordApp
Come on over to the BD support server and we can help you with the problem and get more info. 
https://discord.gg/2HScm8j
