### ISSUE TITLE
I tried to install a theme but it is not showing up

### ISSUE THREAD

**Issue by MostHated** [JsSucks/BetterDiscordApp#280]
Hey there,
    I just found out about this today and wanted to give it a try. I downloaded it, I see it in my discord, but wasn't sure how to install a theme so I looked around and found C:\Users\Me\AppData\Local\BetterDiscord\ext\themes and put it there, I restarted discord but I do not see it in the list?

Did I miss a step or is this not the fork I should be using? The main betterdiscord.net page linked to here, so I thought this was what I should be using since it said the original was no longer maintained.

Thanks!
-MH

**Comment by Mondanzo** [comment]
Nope wrong Repo unless you want to build BDv2 which is still in-development
You actually want to go here https://github.com/rauenzi/BetterDiscordApp/releases and follow this guide if you need more help: https://0x71.cc/bd/guide/

**Comment by MostHated** [comment]
Thanks, I appreciate it. Got it all worked out now!
