### ISSUE TITLE
Can't click any of the buttons in CSS Editor

### ISSUE THREAD

**Issue by DecimusVyycan** [JsSucks/BetterDiscordApp#282]
They open no windows or don't seem to do anything or serve any purpose other than to just sit there. There's no dump file to check, they're just as far as I can tell, not working.

**Comment by Jiiks** [comment]
If you're using the test installer then that doesn't currently have an editor. 
There's a completely new editor being implemented here https://github.com/JsSucks/BetterDiscordApp/tree/bdedit that will be part of the next test release. You can build that branch yourself if you want to test it already.
