### ISSUE TITLE
Emotes do not work.

### ISSUE THREAD

**Issue by snappyapple632** [JsSucks/BetterDiscordApp#302]
Any emotes that are entered are not converted into their respective images, despite emotes being enabled in the settings. The emote lookup tool also does not work.
![Capture](https://user-images.githubusercontent.com/40573129/54063730-557a0900-41c3-11e9-907d-ab5842a5f56a.PNG)
![Capture2](https://user-images.githubusercontent.com/40573129/54063748-704c7d80-41c3-11e9-9b54-6d07331d5409.PNG)

**Comment by Mondanzo** [comment]
Could you check if you have a file called `emotes.json` in your Folder `AppData/Local/BetterDiscord/datastable` ?

**Comment by snappyapple632** [comment]
There is no emotes.json file.

**Comment by satoru8** [comment]
afaik you still need to manually add the emote data.

**Comment by snappyapple632** [comment]
Where do I get a copy of the newest emotes.json?

**Comment by snappyapple632** [comment]
So that explains it. In the meantime, I'll keep this up until this is dealt with.

**Comment by Jiiks** [comment]
Words are no longer replace by emotes, only words with `:` prefix and suffix. autocomplete uses `;`
The render patch for emotes is currently broken iirc but will be fixed soon.

**Comment by snappyapple632** [comment]
Thanks for the info. As I said earlier, I'll keep this open until it is fixed.

**Comment by ElFistoGrande** [comment]
Same issue here. Worked up until a few days back. Tried the emotes.json fix but still nothing):
