### ISSUE TITLE
[Bug] Can't install plugins or themes

### ISSUE THREAD

**Issue by HYPExMon5ter** [JsSucks/BetterDiscordApp#304]
- [x] Used appropriate template for the issue type
- [x] Searched both open and closed issues for duplicates of this issue
- [x] Title adequately and _concisely_ reflects the feature or the bug

**Describe the bug**
So I tried downloading some of the Dummy Plugins/Themes, none of them worked, couldn't preview them either, however I could go to the source. I also tried downloading some of @mwittrien's plugins, none of those worked either, so I don't know if I installed them incorrectly, there's something wrong with bd, or if none of the plugins I downloaded happen to work. The plugins show up in installed, but don't work and there's no settings button like there was in a preview Jikks posted a while back
![image](https://user-images.githubusercontent.com/12315186/54066793-69922a80-4204-11e9-9e8d-3531e477c331.png)

**To Reproduce**
Just try downloading a plugin

**Expected behavior**
The plugin to download/work.

**Screenshots**
![image](https://user-images.githubusercontent.com/12315186/54066804-90e8f780-4204-11e9-932e-867aea13b9fc.png)
Neither of the circled buttons do anything

**System information**
Windows 10, Discord stable, BDV2 2.0.0-beta.5

**Are you willing and able to fix this?**
No, I don't know how to fix it 😛

**Comment by Mondanzo** [comment]
It works for me. Could you try to install it again and if it doesn't prompt something afterwards try to open the source and then installing it again?

**Comment by mwittrien** [comment]
The issue can be closed, all my v2 plugins are not updated to work with the
current v2 built

Karl <notifications@github.com> schrieb am Sa., 9. März 2019, 10:55:
