### ISSUE TITLE
[Bug] Colored text activated at install but not shown as

### ISSUE THREAD

**Issue by berryloop** [JsSucks/BetterDiscordApp#319]
- [x] Used appropriate template for the issue type
- [x] Searched both open and closed issues for duplicates of this issue
- [x] Title adequately and _concisely_ reflects the feature or the bug

**Describe the bug**
In BD 2.00 beta 6 "Colored text" is activated but not shown as

**To Reproduce**
Idk :/ Just installed beta 6 and it happened.

**Expected behavior**
Just not it to be activated.

**System information**
Windows 10 x64
Discord PTB

**Are you willing and able to fix this?**
nope

**Comment by Jiiks** [comment]
Is your intensity set to 0 under `ui->advanced`? It's working fine for me.

**Comment by berryloop** [comment]
It's set to 100. But "Colored Text" was activated right after installing beta 6. But in UI settings it was shown as deactivated.
