### ISSUE TITLE
[Feature] Mac Support

### ISSUE THREAD

**Issue by nathan-fiscaletti** [JsSucks/BetterDiscordApp#322]
- [x] Used appropriate template for the issue type
- [x] Searched both open and closed issues for duplicates of this issue
- [x] Title adequately and _concisely_ reflects the feature or the bug

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when my pepperonis on my frozen pizza aren't aligned perfectly. On the topic of this ticket though: I know that back in the day there was a version of Better Discord that could run on macOS systems. I'm curious if that's still available, or if there are any plans to bring it back?

**Describe the solution you'd like**
That this would work with mac.

**Describe alternatives you've considered**
Not using a mac. But nah, i'm a developer.

**Additional context**
![plz macOs](https://www.iconsdb.com/icons/preview/gray/apple-xxl.png)

**Are you willing and able to implement this?**
Maybe? I'm completely unfamiliar with this code bank.

**Comment by zerebos** [comment]
>Not using a mac. But nah, i'm a developer.

Developers use many different systems, we thankfully aren't locked down to Mac--I myself use Windows. In fact only one of the devs of this project uses Mac.

On that note, BDv2 does actually support Mac. Installer support for Mac is to come at a later time. (Issues for that should be directed towards the installer's repository)

**Comment by nathan-fiscaletti** [comment]
Until the support is added, I found that the [BandagedBD](https://github.com/rauenzi/BetterDiscordApp) fork of [BetterDiscordApp](https://github.com/Jiiks/BetterDiscordApp) seems to work well on mac.

**Comment by zerebos** [comment]
Yeah that's my fork of v1. V2 is still usable using the instructions in the wiki without the installer. 

I'll be closing this but feel free to open it in the installer's repository. Should be JsSucks/BDInstaller
