### ISSUE TITLE
[Bug] - Latest beta wont load plugins

### ISSUE THREAD

**Issue by Plaer1** [JsSucks/BetterDiscordApp#331]
Latest beta wont load plugins?

not sure where they go so I put them in every single better discord folder and made plugin folders / a folder for the plugin in many cases, is there a change in the directory structure/ plugin functionality that prevents/changes plugin loading?

**Comment by zerebos** [comment]
What plugins are you trying to use? You're _very_ likely trying to use plugins from BandagedBD/BDv1 which are not compatible with v2. Remember that v2 is only available for testing of v2 itself right now, not for normal daily usage with plugins/themes as there aren't really any available.

**Comment by ccrowles** [comment]
So which version from the release page is the latest v1? Or should we download BandagedBD instead?

**Comment by zerebos** [comment]
BandagedBD *is* the latest and only maintained version of v1 as stated on our website.
