### ISSUE TITLE
[Issue] Can't uninstall BetterDiscord

### ISSUE THREAD

**Issue by ccrowles** [JsSucks/BetterDiscordApp#334]
I installed Beta 6, without knowing that old plugins and themes do not work. Then I wanted to uninstall but could not find at first how to uninstall it, so I installed BandagedBD hoping it would replace it. It did not. Then I tried installing the stable version, hoping it would replace it. Once again it did not. Then I followed the instructions for uninstalling BetterDiscord as written [here](https://github.com/Jiiks/BetterDiscordApp/wiki/Uninstalling-BD), but it still doesn't work, when I reopen Discord the Beta version is STILL installed. How do I uninstall it?

**Comment by ccrowles** [comment]
I fixed by uninstalling and reinstalling discord itself.

**Comment by HYPExMon5ter** [comment]
You literally just run the installer again and click un-install, glad you figured it out though

**Comment by ccrowles** [comment]
I did run the installer again, but there was no uninstall nor repair option, don't know why. Anyway, thankfully it's solved.
