### ISSUE TITLE
[Bug] Missing bracket in Plugin Example 2

### ISSUE THREAD

**Issue by Puyodead1** [JsSucks/BetterDiscordApp#336]
Extremely minor so I though i should just make an issue, there is a missing bracket in Plugin Example 2
``module.exports = (Plugin, Api, Vendor) =>``

**Comment by zerebos** [comment]
If I recall correctly Example 2 is our syntax error test (i.e. test that invalid modules are caught correctly) which would make that intentional. Correct me if I'm wrong @jiiks

**Comment by Puyodead1** [comment]
Okay, just wasn't sure. I use that example for base code in plugins and noticed that. Thanks.
