### ISSUE TITLE
[Bug] Installer doesn't install BetterDiscord

### ISSUE THREAD

**Issue by Spencer-0003** [JsSucks/BetterDiscordApp#340]
The installer says that it is installed but I don't have any of the BD features.

**Comment by Kyza** [comment]
Ctrl+B

**Comment by Spencer-0003** [comment]
I just install then press Ctrl+B?

**Comment by Kyza** [comment]
Install, open Discord, press Ctrl+B. If you are looking for something with maintained plugins and themes this is not it. BetterDiscord v2 is still in beta and is not for everyday use.

**Comment by Kyza** [comment]
Can someone close this, please?

**Comment by Kein** [comment]
Is latest master even capable hooking up and loading properly? It tries to load `client/dist/betterdiscord.client.js` but there is no such file. There is `client/dist/betterdiscord.client-release.js` but renaming it leads to another file not found for loading.

**Comment by zerebos** [comment]
Installer issues belong at https://github.com/JsSucks/BDI

**Comment by Kein** [comment]
I'm not using an installer, I'm using the injection variant. And my question wasnt' about the installer though, I've only used this issue to avoid creating junk issue thread.
