### ISSUE TITLE
BDV2 MINOR Bug [Bug]

### ISSUE THREAD

**Issue by Ianardo-DiCaprio** [JsSucks/BetterDiscordApp#343]
- [x] Used appropriate template for the issue type
- [x] Searched both open and closed issues for duplicates of this issue
- [x] Title adequately and _concisely_ reflects the feature or the bug

**Describe the bug**

In the installer a lot of the text with characters that go down more {g, y, etc etc } is clipped off and the `Browse` buttons when you click options is also clipped at the top and bottom on 4k monitors. I dragged it over to my 1920x1080 monitor and it wasn't clipped so it's just 4k.
**To Reproduce**

Install on a 4k monitor
**Expected behavior**

Unclipped letters
**Screenshots**

![image](https://user-images.githubusercontent.com/43935737/56472320-cfeda800-6454-11e9-9d57-a00521526d1d.png)
![image](https://user-images.githubusercontent.com/43935737/56472322-e0058780-6454-11e9-996f-71d269759d2e.png)

**System information**

Windows 10, Canary.
**Additional context**

Only happens on 4k monitors.
**Are you willing and able to fix this?**

Nope

**Comment by zerebos** [comment]
@Jiiks can you transfer this issue to the BDI repo? I don't seem to have the perms to.
