### ISSUE TITLE
[Bug] Can't implement themes even if images are in themes folder

### ISSUE THREAD

**Issue by OPAmqericaHPE** [JsSucks/BetterDiscordApp#344]
This is insane. For some reason, BetterDiscord doesn't detect any images I put in its themes folder. I have googled images that are good for themes. When I drag and drop them into my themes folder, BetterDiscord doesn't detect these files.

**Comment by qwerasd205** [comment]
1. You're likely on the wrong repo, you should be using [Bandaged BD](https://github.com/rauenzi/BetterDiscordApp/releases) if you're not.
2. Images are not themes. Themes require CSS; images alone do not work as themes. You can find themes on the BetterDiscord Discord server. For info on installing themes you can refer to [this guide](https://0x71.cc/bd/guide/#install-theme-win).

**Comment by zerebos** [comment]
Please read the above. @OPAmqericaHPE
