### ISSUE TITLE
[Feature] Add Building Instructions

### ISSUE THREAD

**Issue by 5HT2** [JsSucks/BetterDiscordApp#351]
- [x] Used appropriate template for the issue type
- [x] Searched both open and closed issues for duplicates of this issue
- [x] Title adequately and _concisely_ reflects the feature or the bug

**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

Add to readme

**Describe alternatives you've considered**

Reading the parent fork, different release type / missing instructions

**Additional context**

N/A.

**Are you willing and able to implement this?**

Yes

**Comment by zerebos** [comment]
This actually exists already in the wiki https://github.com/JsSucks/BetterDiscordApp/wiki/Building

**Comment by 5HT2** [comment]
Can we please add this to and readme, and at the same time fill it out so it's more useful to people glancing at the project?

**Comment by intrnl** [comment]
It'd be better not to, people kept following our tracks and ended up where they're not supposed to be meddling *yet*.
