### ISSUE TITLE
Activity tab doesn't scale well with 3 columns 

### ISSUE THREAD

**Issue by solonovamax** [JsSucks/BetterDiscordApp#355]
Whenever you go to the "Home" tab, then click on "Activity", and resize your window (horizontally), and there are 3 columns, some columns will be cut off.

![image](https://user-images.githubusercontent.com/46940694/59969363-a36c1000-9519-11e9-904b-1a139c8cdb14.png)

Does not happen when there are 2 columns.

I am currently using a Windows 10 pc.

**Comment by zerebos** [comment]
And how is this an issue with BetterDiscord V2?

**Comment by solonovamax** [comment]
> And how is this an issue with BetterDiscord V2?

Hey, sorry to take so long to respond, it's just it cuts off some of the columns when I have it on my 2nd screen. I'm currently using Bandaged BD, or BetterDiscord V2 (I think?).

I'm sorry if anything I said earlier was unclear.

**Comment by zerebos** [comment]
Please check whether the same thing occurs without BD
