### ISSUE TITLE
[Feature] [Question] Telemetry Removal and Privacy Protection

### ISSUE THREAD

**Issue by 7MXek** [JsSucks/BetterDiscordApp#364]
I didn't see anything regarding privacy protections or disabling telemetry within this project, but that was only with a cursory glance. I specifically hate that Discord has the ability to scan any running programs on my system. I found a similar project (EnhancedDiscord) that has these anti-spyware features, but I'd like to use BetterDiscord due to some specific plugins that I would love to use (DiscordCrypt).

So, does BetterDiscord completely disable Discord's telemetry or provide us with a better way to safeguard our privacy already, is that a planned feature, or is it not in the roadmap?

**Comment by zerebos** [comment]
This is not the right location for this question as this repo is not active, but there is a plugin that does that for the current version of BetterDiscord. [DoNotTrack](https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/DoNotTrack)

**Comment by 7MXek** [comment]
Thank you for your quick and informative answer.

Where is the currently active BetterDiscord repo? I followed the github pages link for the original project, then to the forked version linked there (to here), but I don't see any further information regarding an active BetterDiscord repo.

**Comment by zerebos** [comment]
This is for the development of a completely rewritten version under the direction of Jiiks, but as you can see it has gone stale. The currently active fork for the currently usable version is here: https://github.com/rauenzi/BetterDiscordApp

Also linked from the website http://betterdiscord.net/

**Comment by 7MXek** [comment]
I see. Thank you for clearing up my misunderstanding.

**Comment by zerebos** [comment]
No problem at all, it happens a lot. Wish I could go through and clean out all the old repos and such but alas I don't have access.
