### ISSUE TITLE
[Bug] Constant crashing

### ISSUE THREAD

**Issue by ghost** [JsSucks/BetterDiscordApp#365]
- [x] Used appropriate template for the issue type
- [x] Searched both open and closed issues for duplicates of this issue
- [x] Title adequately and _concisely_ reflects the feature or the bug

**Describe the bug**
Discord crashes all the time to the We tracked the problem screen on BetterDiscord Beta 6

**To Reproduce**
Use Discord.
It sometimes does it when I hover over the BetterDiscord button/menu

**Expected behavior**
It crashes

**Screenshots**
I dont use github that much so i dont know how to add screenshots

**System information**
Windows 10 Insider, BetterDiscord 2.0.0 Beta 6

**Additional context**

I have no additional context.

**Are you willing and able to fix this?**

No I am not. All knowledge I have is just basic scripting.

**Comment by SemexDevelopment** [comment]
same for me right now

**Comment by zerebos** [comment]
Duplicate of #342
