### ISSUE TITLE
Discord Keeps Crashing on newest version.[Bug]

### ISSUE THREAD

**Issue by ItzNxthaniel** [JsSucks/BetterDiscordApp#366]
- [ ] Used appropriate template for the issue type
- [ ] Searched both open and closed issues for duplicates of this issue
- [ ] Title adequately and _concisely_ reflects the feature or the bug

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information**

**Additional context**

**Are you willing and able to fix this?**

**Comment by zerebos** [comment]
Duplicate of #342
