### ISSUE TITLE
[Bug] BTDiscord doesn't work anymore

### ISSUE THREAD

**Issue by TotoShampoin** [JsSucks/BetterDiscordApp#367]
**Describe the bug**
Not even a bug at this point, BetterDiscord doesn't start up with Discord anymore

**To Reproduce**
Boot Discord, and BetterDiscord won't start up

**Expected behavior**
It's supposed to start up with Discord, and load the plugins

**System information**

Win10, with the latest Discord update.

**Additional context**
I'd assume it's an update issue

**Are you willing and able to fix this?**
I'm not able to fix it at all

**Comment by crow-bit** [comment]
with that whole qol update, I'm not surprised, but the change log didn't really say anything that they updated that would break BD so it's weird. hopefully they'll get around to fixing it soon.

**Comment by tale** [comment]
BetterDiscord atm is unmaintained, it hasn't worked for a few months now. Use BandagedBD 
[Link](https://github.com/rauenzi/BetterDiscordApp/releases)

**Comment by Dhveszak** [comment]
I have the same problem, with both Better Discord and BandagedBD. None of them is working at all, not even the "BD" white and blue logo flashing in the bottom right corner

**Comment by tale** [comment]
This isn't the place to talk about it go to https://github.com/rauenzi/BetterDiscordApp
