### ISSUE TITLE
Doesn't work with cyrillic paths

### ISSUE THREAD

**Issue by ArcherZett** [JsSucks/BetterDiscordApp#374]
error screenshot
![345345](https://user-images.githubusercontent.com/39631936/79278468-68760700-7eb4-11ea-8f68-988a135ff52a.PNG)

**Comment by qwerasd205** [comment]
This repo is effectively abandoned. If you need BetterDiscord use [BandagedBD](https://github.com/rauenzi/BetterDiscordApp).
