### ISSUE TITLE
Channel/Server loading visual bug

### ISSUE THREAD

**Issue by elvis-p1** [JsSucks/BetterDiscordApp#380]
When loading different channels the normal discord ui shows up for a second, looks strange. It hasn't done this before. If the channel loads faster it doesn't show up/doesn't show for long. It goes back to normal once the channel fully finishes loading.

**Screenshots**
![bugreport](https://user-images.githubusercontent.com/57242523/90435206-b1291100-e09c-11ea-8e5c-4f3bd368e95f.png)

**Comment by zerebos** [comment]
This is the wrong repository.
