### ISSUE TITLE
[Bug] Plugins and themes don't work.

### ISSUE THREAD

**Issue by Relanses** [JsSucks/BetterDiscordApp#381]
Plugins and themes do not work on [Windows 10 64-Bit (10.0.19041)].
When i'm enable a plugin or theme, nothing just changes.

**Comment by octopusknives** [comment]
You are either in the wrong place, or you are using a broken; dead version of BetterDiscord (this repo). You probably want to be here https://github.com/rauenzi/BetterDiscordApp.

**Comment by Relanses** [comment]
Is this an old version?
![Screenshot_5](https://user-images.githubusercontent.com/69887688/90601042-38db6080-e200-11ea-88c5-80667a3ad83b.png)

**Comment by zerebos** [comment]
That is the version pointed to by AlexHaber https://github.com/rauenzi/BetterDiscordApp
