### ISSUE TITLE
Swap reCAPTCHA with hCaptcha

### ISSUE THREAD

**Issue by fourteentrees** [JsSucks/BetterDiscordApp#387]
**Is your feature request related to a problem? Please describe.**
The problem: Discord swapped the login CAPTCHA to hCaptcha.

**Describe the solution you'd like**
Update the injection. Switch reCAPTCHA to hCaptcha since it seems to break the client's login.

**Are you willing and able to implement this?**
Was originally going to, but I don't know where the login screen is stored

**Comment by qwerasd205** [comment]
This repo has been dead for nearly 2 years now. You might be on the wrong repo. Additionally, no version of BetterDiscord has anything to do with the login process.
