### ISSUE TITLE
Latest Update Broke BBD[Bug]

### ISSUE THREAD

**Issue by Wizerdz** [JsSucks/BetterDiscordApp#390]
Breats

**Comment by Wizerdz** [comment]
wrong one

**Comment by progamingguide** [comment]
yup same for me BBD doesn't show up anymore after restarting discord. reinstalled it multiple times and even reinstalled discord.

**Comment by AnthraxRobin** [comment]
Same issue here

**Comment by Bhutch9000** [comment]
same

**Comment by EJintheCloud** [comment]
same

**Comment by Sansibar1234** [comment]
after discord update, my discord acted like it was the browser version. Had to delete BetterDiscord to fix it

Now im waiting for a BD Update

**Comment by temmem** [comment]
> after discord update, my discord acted like it was the browser version. Had to delete BetterDiscord to fix it
> 
> Now im waiting for a BD Update

my discord had the same thing happen to it.

**Comment by raffel080108** [comment]
Yup happening same thing by me, please fix this asap!!

**Comment by LetsGetRemixed** [comment]
My discord has been stuck in the browser mode bug for a week now, The PBT has been broken for months. When is this getting fixed????

**Comment by zerebos** [comment]
This repository is abandoned. Please refer to https://github.com/rauenzi/BetterDiscordApp
